# Generated by Django 4.0 on 2022-01-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('create_date', models.DateField()),
                ('update_date', models.DateField()),
                ('image', models.ImageField(default=' ', upload_to='shop/images')),
            ],
        ),
    ]
